# Numpy
Numpy is a general- purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains among other things:
    1. a powerful N-dimensional array object
    2. sophisticated (broadcasting) fucntions
    3. tools for integrating C/C++ and Fortran code
    4. useful for linear algebra, Fourier transform, and random number capabilities
    
Beside its obvious scientific uses, numpy can also be usedas an efficient multi-dimensional container for generic data. Arbitrary data-type can be defined. This allows numpy to seamlessly and speedliy integrate with a wide variety of databases.

### Installation:
    pip install numpy
   
### How to use
    import numpy as np

# Arrays in NumPy
Numpy's main object is the homogenous multidimensional array.
It ia atble of elements(usually numbers), all of the same type, indexed by a tuple of positive integers.
In numpy dimensions are called axes. The number of axes is rank
Numpy's array class is called ndarray. It is also known by the alias array.

For example:
    [[1,2,3],
    4,2,5]]
    This array has: rank=2 (as it is 2-dimensional or it has 2 axes)
    first dimensional(axis) length=2, second dimension has length =3
    overall shape can be expressed as: (2,3)
    

In [14]:
import numpy as np

In [15]:
# creating array object
arr=np.array([[1,2,3],
             [4,2,5]])

In [16]:
# printing type of array
type(arr)

numpy.ndarray

In [17]:
#printing array dimensions(axes)
arr.ndim

2

In [18]:
#printing shape of array
arr.shape

(2, 3)

In [19]:
#printing size(total elements) of array
arr.size

6

In [20]:
#printing type of elements in array
arr.dtype

dtype('int32')

In [22]:
arr1=np.array([1,2,3])
arr1.shape

(3,)

# Array creation

In [24]:
# creating array from list with type float
a=np.array([[1,2,4],[5,8,7]],dtype='float')
print(a)

[[1. 2. 4.]
 [5. 8. 7.]]


In [27]:
#creating array from tuple
b=np.array((1,2,3))
print(b)

[1 2 3]


In [28]:
#creating a 3*4 array with all zeros
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#creating a constant calue array of complex type
d=np.full((3,3),6,dtype='complex')
print(d)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [30]:
#creating an array with random values
e=np.random.random((2,2))
print(e)

[[0.23921718 0.70845279]
 [0.54153063 0.15821589]]


In [31]:
#creating array with all values as 1
f=np.ones((3,4))
print(f)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
#creating identity array
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.arange? # prss shift+enter

In [37]:
#creating a sequence of integers from 0 to 30 with steps of 5
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [38]:
#creating a sequence of 10 values in range 0 to 5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [42]:
#reshaping 3*4 array to 2*2*3 array
arr=np.array([[1,2,3,4],
            [5,2,4,2],
            [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print(arr)
print()
print(newarr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [46]:
#flatten array
arr=np.array([[1,2,3],[4,5,6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6])

# Array Indexing
Numpy offers many ways to do array indexing:

In [47]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])

In [54]:
#slicing
temp=arr[:2,::2]       # [row,colum] (srat:end+1:step)
print(temp)

[[-1.  0.]
 [ 4.  6.]]


In [55]:
#Integer array indexing
temp=arr[[0,1,2,3],[3,2,1,0]] #elements at indices (0.3),(1,2),(2,1),(3,0)
print(temp)

[4. 6. 0. 3.]


In [57]:
#Boolean array indexing
cond=arr>0
temp=arr[cond]
print(temp)

[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# Basic Operations

In [58]:
a=np.array([1,2,5,3])

In [59]:
#add 1 to each element
print(a+1)

[2 3 6 4]


In [60]:
#subtract 3 from each elemnt
print(a-3)

[-2 -1  2  0]


In [61]:
#multiply each elemnt by 10
print(a*10)

[10 20 50 30]


In [62]:
#square each element
print(a**2)

[ 1  4 25  9]


In [63]:
#modify existing array
a*=2
print(a)

[ 2  4 10  6]


In [65]:
#transpose of array
b=np.array([[1,2,3],[3,4,5],[9,6,0]])
print(b.T)

[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [67]:
arr=np.array([[1,5,6],[4,7,2],[3,1,9]])
print(arr.max())
print(arr.max(axis=1))  #row-wise maximum

9
[6 7 9]


In [70]:
print(arr.min(axis=0))  #column-wise minimum

[1 1 2]


In [71]:
print(arr.sum())

38


In [72]:
print(arr.cumsum(axis=1))   #cumulative sum along each row

[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [74]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
print(a+b)
print(a*b)   #element-wise multiplication
print(a.dot(b))   #matrix multiplication

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


In [75]:
a=np.array([0,np.pi/2,np.pi])
print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [76]:
a=np.array([0,1,2,3])
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [77]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

# Sorting

In [80]:
a=np.array([[1,4,2],[3,4,6],[0,-1,5]])
#sorted array
print(np.sort(a,axis=None))
#rowwise sorted array
print(np.sort(a,axis=1))
#specifying sorting algorithm
print(np.sort(a,axis=0,kind='mergesort'))


[-1  0  1  2  3  4  4  5  6]
[[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
[[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [84]:
#sorting of structured array
dtypes=[('name','S10'),('grad_year',int),('cgpa',float)]
values=[('Meghna',2024,8.77),('Kaushik',2020,8.98),('Shiva',2027,6.8)]
arr=np.array(values,dtype=dtypes)
print(arr)

[(b'Meghna', 2024, 8.77) (b'Kaushik', 2020, 8.98) (b'Shiva', 2027, 6.8 )]


In [86]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
#vertical stacking
print(np.vstack((a,b)))
#horizontal stacking
print(np.hstack((a,b)))
c=[5,6]
#stacking colums
print(np.column_stack((a,c)))
#concatenation method
print(np.concatenate((a,b),1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5]
 [3 4 6]]
[[1 2 5 6]
 [3 4 7 8]]


In [88]:
a=np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])
#horizontal splitting
print(np.hsplit(a,2))
#vertical splitting
print(np.vsplit(a,2))

[array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]
[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [89]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [91]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [98]:
c=np.array([1,5,4,2,0])
print(np.median(c))
print(np.mean(c))
w=np.array([1,1,1,1,1])
print(np.average(c,weights=w))
#weighted avg=n1*w1 + n2*w2 + n3*w3/n1+n1+n3
#standard deviation
u=np.mean(c)
mystd=np.sqrt(np.mean(abs(c-u)**2))
print(mystd)
print(np.std(c))
#variance
print(mystd**2)
print(np.var(c))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


In [101]:
a=np.arange(10)+5
print(a)
np.random.seed(1)
np.random.shuffle(a)
print(a)
a=np.random.randn(2,3)
print(a)
a=np.random.randint(5,10,3)
print(a)
element=np.random.choice([1,4,3,2,11,27])
print(element)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
